name: Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/snake.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: WaelHammali
          outputs: |
            profile-snake/github-snake-dark.svg?palette=github-dark
            profile-snake/github-snake.svg

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: regenerate contribution snake"
          file_pattern: "profile-snake/*.svg"
